### ISSUE TITLE
Python KeyError: 'Token'

### ISSUE THREAD

**Issue by Binternet** [MayaraCloud/apt-transport-s3#45]
Running a fresh instance with and getting this error:

```
root@ip-192-168-29-8:/etc/apt# apt update
Region: eu-west-1
Using config file for credentials
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 551, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 364, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 171, in get_credentials
    self.token = data['Token']
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'Token'
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
E: Method s3 has died unexpectedly!
```

What's the `Token` entry for?

**Comment by Binternet** [comment]
Wops, now saw this:
https://github.com/MayaraCloud/apt-transport-s3/issues/31
