### ISSUE TITLE
Python KeyboardInterrupt

### ISSUE THREAD

**Issue by Binternet** [MayaraCloud/apt-transport-s3#46]
`s3auth.conf` holds only Region and Token:

```
root@ip-192-168-29-8:/etc/apt# cat s3auth.conf
Region = 'eu-west-1'
Token = ''
```

yet when running `apt update` this fires:
```
root@ip-192-168-29-8:/etc/apt# apt update
Region: eu-west-1
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 553, in <module>
    sys.exit(ret)
KeyboardInterrupt
Region: eu-west-1
```

**Comment by vorlock** [comment]
Which version are you using @Binternet ?

**Comment by Binternet** [comment]
`apt-transport-s3/bionic,now 1.3.0-1 all [installed]`

Seems to be fine now, it only outputs the region twice:
```
root@ip-192-168-29-8:/home/ubuntu# apt update
Region: eu-west-1
Region: eu-west-1
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
```

**Comment by Binternet** [comment]
Looks like it's still happening, for example when I ran using `--fix-missing` flag:

```
root@ip-192-168-29-8:/home/ubuntu# apt update --fix-missing
Region: eu-west-1
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 553, in <module>
    sys.exit(ret)
KeyboardInterrupt
Region: eu-west-1
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
```

**Comment by vorlock** [comment]
Can you try the latest one?

**Comment by dpryden** [comment]
Given that the stack trace seems to show a `KeyboardInterrupt` from inside `sys.exit`, I wonder if it's just a race condition between this script shutting down normally (once stdin is a closed pipe) and APT killing it with a SIGINT (from `pkgAcquire::Worker::~Worker()` in `apt-pkg/acquire-worker.cc`).

Possibly the main block should do `signal.signal(signal.SIGINT, signal.SIG_IGN)` after `method.run()` returns, so that any SIGINT that occurs after that point doesn't cause an interrupt, the process just runs to completion normally.
