### ISSUE TITLE
Exception: URL error reason: unknown url type: arn

### ISSUE THREAD

**Issue by sp-andres-diaz** [MayaraCloud/apt-transport-s3#49]
Hi,

I got this error when perform an `apt-get update` :
```
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 556, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 369, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 159, in get_credentials
    raise Exception("URL error reason: %s" % e.reason)
Exception: URL error reason: unknown url type: arn
```

As far as I see, the problem is related in the way of how request is made in line 190 (master branch):

```data = self.__request_json(urllib.parse.urljoin(self.credentials_metadata, self.iamrole))```

In my case `self.credentials_metadata` has the correct value (i.e. `http://169.254.169.254/latest/meta-data/iam/security-credentials/`), but the `self.iamrole` has the following format: `arn:aws:iam::00000000:role/xxxx`, as a result, the urljoin return only the iamrole (because of the format with `:`).

Interactive example:
```
x = "http://foo.bar/path/"
y = "arn:something"
import urllib.parse
urllib.parse.urljoin(x,y)

'arn:something'
```

Note that if you change `arn:xxxx` by any other prefix (i.e: `abc:123`) the problem does not appear.

As workaround I substitute the `urljoin` function by a simple `str.join` function.

**Comment by vorlock** [comment]
Which version of apt-transport-s3 were you using when noticed the above? To me looks like it was pre 2.0.0, right?

**Comment by sp-andres-diaz** [comment]
Yes, appears to be version 1.3.0:
```dpkg -l | grep s3
ii  apt-transport-s3                      1.3.0-1                                                  all          APT transport for privately held AWS S3 repositories
```

**Comment by vorlock** [comment]
Is this still the case in version 2.0.0 for you?

**Comment by paul-civitas** [comment]
This occurs because sometimes `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/` returns a role NAME and sometimes it returns a role ARN.

When it returns a role ARN apt-transport-s3 freaks out.

I don't know why it will return a name sometimes and an ARN other times. Still researching.

**Comment by paul-civitas** [comment]
To fix this you need a urlencode here: https://github.com/MayaraCloud/apt-transport-s3/blob/development/s3#L112
