### ISSUE TITLE
Support for EC2 Instance Metadata V2 (IMDSv2)

### ISSUE THREAD

**Issue by fred-vogt** [MayaraCloud/apt-transport-s3#53]
apt-transport-s3 currently won't work with instance profiles if IMDSv2 is enabled.

If IMDSv2 is enabled a session token is required to query IMDS.

IMDSv2 is either 'optional' or 'required'.  Thus it should be safe to always assume its available.

`/etc/apt/s3auth.conf` might possibly need an option to switch this on/off.

```bash
# Get a token
IMDSv2_TOKEN=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 300" -sL "http://169.254.169.254/latest/api/token")

# Queries require the token
curl -H "X-aws-ec2-metadata-token:$IMDSv2_TOKEN" -sL http://169.254.169.254/latest/meta-data/...
```

## ec2-metadata lib
This python library supports IMDSv2.  It uses `requests`, but can serve as a python reference.  
* https://pypi.org/project/ec2-metadata/
  * https://github.com/adamchainz/ec2-metadata/blob/master/src/ec2_metadata.py

## Background
* [2019/11 announcing amazon ec2 instance-metadata service updates](https://aws.amazon.com/about-aws/whats-new/2019/11/announcing-updates-amazon-ec2-instance-metadata-service/)
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
* https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by fred-vogt** [comment]
Not when IMDSv2 is enabled you'll get a 401 currently if relying on IAM role creds, and didn't specify region in config file:
```
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 116, in __request_json
    response = urllib.request.urlopen(request, None, 30)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 596, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 383, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 177, in get_credentials
    self.region = self.__get_region(data)
  File "/usr/lib/apt/methods/s3", line 141, in __get_region
    region = self.__request_json(self.instance_metadata)['region']
  File "/usr/lib/apt/methods/s3", line 127, in __request_json
    raise Exception("URL error reason: %s" % e.reason)
Exception: URL error reason: Unauthorized
```
