### ISSUE TITLE
TypeError: decoding str is not supported

### ISSUE THREAD

**Issue by salemgolemugoo** [MayaraCloud/apt-transport-s3#63]
I'm trying setup with IAM role and get this error:
```
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 597, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 384, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 191, in get_credentials
    str(self.credentials_metadata, 'utf-8'),
TypeError: decoding str is not supported
```

while `apt update`

**Comment by salemgolemugoo** [comment]
IMDS2 is optional

**Comment by vorlock** [comment]
This should be fixed now
