### ISSUE TITLE
Create new release from master due to str errors in get_credentials() method

### ISSUE THREAD

**Issue by andrejskuidins** [MayaraCloud/apt-transport-s3#67]
I have an issue in Ubuntu with:

```
        if data.get("AccessKeyId") is None:
            self.__get_role()
            data = self.__request_json(urllib.parse.urljoin(self.credentials_metadata,
                                                            str(self.iamrole, 'utf-8')))
```
Following command:
```
root@ip-10-200-197-172:~# apt update
Traceback (most recent call last):
  File "/usr/lib/apt/methods/s3", line 639, in <module>
    method = S3_method(config)
  File "/usr/lib/apt/methods/s3", line 426, in __init__
    self.iam.get_credentials()
  File "/usr/lib/apt/methods/s3", line 234, in get_credentials
    str(self.iamrole, 'utf-8')))
TypeError: decoding str is not supported
Reading package lists... Done
E: Method s3 has died unexpectedly!
E: Sub-process s3 returned an error code (1)
E: Method /usr/lib/apt/methods/s3 did not start correctly
E: Failed to fetch s3://kube-majik-venus-dev-packages-ubuntu-20-repo/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
I need this fix in 2.2.0:
https://github.com/MayaraCloud/apt-transport-s3/blame/development/s3#L262-L264

**Comment by msdrigg** [comment]
I'd also love to see this!

**Comment by vorlock** [comment]
Done
